### PR TITLE
Added lexicon based scoring and tfidf

### PR DESCRIPTION
**Pull request by rachitjain2706**

### CODE REVIEW

**Comment by ykl7** [comment]
This looks ok. Are you going ahead with implementing what we discussed @rachitjain2706 ?

**Comment by rachitjain2706** [comment]
Yes. I am implementing it according to what we had discussed. I will be updating with newer changes soon.

**Comment by ykl7** [comment]
Please build on this PR itself. I'm marking it as in-progress for the moment

**Comment by ykl7** [comment]
@rachitjain2706 I would suggest trying out ```CountVectorizer``` or even ```GloVe``` embeddings as an alternate to ```TFIDF``` (do not stop pursuing it though). Also, I think it would benefit you to write your own tokenizer as per your dataset which the vectorizer function would then use. Kindly ask for clarification of whatever other problems (approach or otherwise) you have run into.

**Comment by ykl7** [comment]
@rachitjain2706 further work going on, right?

**Comment by rachitjain2706** [comment]
Yes. Making a feature set

**Pull request merged**
